# OAuth 开发环境配置
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      password:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 20  # 最大连接池大小
      minimum-idle: 10         # 最小空闲连接数
      idle-timeout: 30000     # 连接在池中的最大空闲时间，单位为毫秒
      max-lifetime: 1800000   # 连接的最大生命周期，单位为毫秒
      connection-timeout: 30000 # 从连接池获取连接的超时时间，单位为毫秒
    url: jdbc:p6spy:mysql://localhost:3306/focus_admin?serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: JZ8Qrd,ZlkPHs
  elasticsearch:
    enabled: false


# 日志配置
logging:
  level:
    com.focus: debug
    org.springframework: info
